export const API_ENDPOINTS = {
  auth: {
    managerLogin: '/auth/manager/login',
    employeeLogin: '/auth/employee/login',
    currentUser: '/auth/me',
    logout: '/auth/logout',
    deleteAccount: '/auth/account',
    verifyTwoFactor: '/auth/2fa/verify',
    twoFactorStatus: '/auth/2fa/status',
    twoFactorSetup: '/auth/2fa/setup',
    twoFactorEnable: '/auth/2fa/enable',
    twoFactorDisable: '/auth/2fa/disable',
    changePassword: '/auth/password',
    sessions: '/auth/sessions',
    revokeOtherSessions: '/auth/sessions/revoke-others',
  },
  settings: {
    get: '/settings',
    updateSection: (section) => `/settings/${section}`,
  },
  notifications: {
    list: '/notifications',
    markRead: (id) => `/notifications/${id}/read`,
  },
  auditLogs: {
    list: '/audit-logs',
  },
  dashboard: {
    summary: '/dashboard/summary',
  },
  manager: {
    workbench: '/manager/candidate-workbench',
    scheduleInterview: '/manager/interview-schedule',
    scheduleIcs: (id) => `/manager/interview-schedule/${id}/ics`,
    sendCommunication: '/manager/communications/send',
    enhanceCommunication: '/manager/communications/enhance',
    updateCandidateProfile: (id) => `/manager/candidates/${id}/profile`,
  },
  employees: {
    list: '/employees',
    detail: (id) => `/employees/${id}`,
  },
  assessments: {
    list: '/assessments',
    detail: (id) => `/assessments/${id}`,
    pdf: (id) => `/assessments/${id}/pdf`,
    share: (id) => `/assessments/${id}/share`,
    shared: (token) => `/assessments/share/${token}`,
    sharedPdf: (token) => `/assessments/share/${token}/pdf`,
  },
  interviews: {
    retention: '/interviews/retention',
  },
  roles: {
    list: '/roles',
    detail: (id) => `/roles/${id}`,
  },
  rubrics: {
    list: '/rubrics',
    detail: (id) => `/rubrics/${id}`,
  },
  assessmentTemplates: {
    list: '/assessment-templates',
    detail: (id) => `/assessment-templates/${id}`,
  },
  reports: {
    summary: '/reports',
  },
  leaderboard: {
    summary: '/leaderboard',
  },
  employee: {
    journey: '/employee/journey',
    profile: '/employee/profile',
    resume: '/employee/resume',
    resumeAnalyze: '/employee/resume/analyze',
    resumeJobMatch: '/employee/resume/job-match',
    resumeIndex: '/employee/resume-index',
    resumeManage: (employeeId) => `/employee/resume/${employeeId}`,
    resumeDownload: (employeeId) => `/employee/resume/${employeeId}/download`,
    resumeView: (employeeId) => `/employee/resume/${employeeId}/view`,
    domains: '/employee/domains',
    interviewQuestions: '/employee/interview/questions',
    interviewSession: '/employee/interview/session',
    interviewChat: '/employee/interview/chat',
    interviewComplete: '/employee/interview/complete',
    assessments: '/employee/assessments',
    assessmentStart: (id) => `/employee/assessments/${id}/start`,
    assessmentSubmit: (id) => `/employee/assessments/${id}/submit`,
    assessmentHistory: '/employee/assessments/history',
    feedback: '/employee/feedback',
    interview: {
      start: '/employee/interview/start',
      uploadResume: '/employee/interview/upload-resume',
      extractSkills: '/employee/interview/extract-skills',
      getQuestion: '/employee/interview/question',
      submitAnswer: '/employee/interview/answer',
      complete: '/employee/interview/complete',
      getResults: (interviewId) => `/employee/interview/${interviewId}/results`,
      history: '/employee/interview/history',
    },
  },
}
